# @Author: Brogan Miner <Brogan>
# @Date:   2019-05-05T17:45:07-07:00
# @Email:  brogan.miner@oregonstate.edu
# @Last modified by:   Brogan
# @Last modified time: 2019-05-07T20:05:06-07:00

AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: DB access wrappers for OSU Sustainability Office

Metadata:
  AWS::ServerlessRepo::Application:
    Name: OSUSORootApp
    Description: Root application for OSU SO Nested Stack
    Author: Brogan Miner
    HomePageUrl: https://github.com/OSU-Sustainability-Office/lambda-common-layer
    SemanticVersion: 1.0.0 # Refer to here for semantic versioning: https://semver.org/

Globals:
  Function:
    Timeout: 3
    Runtime: nodejs10.x
  Api:
    Cors: 
        AllowMethods: "'POST, GET'"
        AllowHeaders: "'X-Forwarded-For'"
        AllowOrigin: "'oregonstate.edu'"
        MaxAge: "'600'"
        AllowCredentials: True

Resources:
  AuthLogin:
    Type: AWS::Serverless::Function
    Properties:
      MemorySize: 128
      CodeUri: Auth/
      Handler: app.login
      Layers:
        - !Ref LambdaCommonLayer
      Events:
        Login:
          Type: Api
          Properties:
            Path: /login
            Method: get
  AuthUser:
    Type: AWS::Serverless::Function
    Properties:
      MemorySize: 128
      CodeUri: Auth/
      Handler: app.checkCookie
      Layers:
        - !Ref LambdaCommonLayer
      Events:
        Login:
          Type: Api
          Properties:
            Path: /user
            Method: get
  AuthLogout:
    Type: AWS::Serverless::Function
    Properties:
      MemorySize: 128
      Policies:
        - AmazonDynamoDBFullAccess
      CodeUri: Auth/
      Handler: app.logout
      Layers:
        - !Ref LambdaCommonLayer
      Events:
        Login:
          Type: Api
          Properties:
            Path: /logout
            Method: get
  AuthSession:
    Type: AWS::Serverless::Function
    Properties:
      MemorySize: 128
      Policies:
        - AmazonDynamoDBFullAccess
      CodeUri: Auth/
      Handler: app.session
      Layers:
        - !Ref LambdaCommonLayer
      Events:
        Login:
          Type: Api
          Properties:
            Path: /session
            Method: get
  LambdaCommonLayer:
        Type: AWS::Serverless::LayerVersion
        Properties:
            LayerName: LambdaCommonLayer
            Description: common layer
            ContentUri: dependencies/
            CompatibleRuntimes:
              - nodejs6.10
              - nodejs8.10
              - nodejs10.x
            LicenseInfo: 'MIT'
            RetentionPolicy: Retain
